// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: wkf.proto

package wkf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// classify start
type ClassifyListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ClassifyListReq) Reset() {
	*x = ClassifyListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyListReq) ProtoMessage() {}

func (x *ClassifyListReq) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyListReq.ProtoReflect.Descriptor instead.
func (*ClassifyListReq) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ClassifyListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ClassifyListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassifyId int64  `protobuf:"varint,1,opt,name=classifyId,proto3" json:"classifyId,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreateBy   int64  `protobuf:"varint,3,opt,name=createBy,proto3" json:"createBy,omitempty"`
	CreatedAt  string `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdateBy   int64  `protobuf:"varint,5,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	UpdatedAt  string `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *ClassifyListData) Reset() {
	*x = ClassifyListData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyListData) ProtoMessage() {}

func (x *ClassifyListData) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyListData.ProtoReflect.Descriptor instead.
func (*ClassifyListData) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyListData) GetClassifyId() int64 {
	if x != nil {
		return x.ClassifyId
	}
	return 0
}

func (x *ClassifyListData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassifyListData) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *ClassifyListData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ClassifyListData) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *ClassifyListData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ClassifyListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64               `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Data  []*ClassifyListData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ClassifyListResp) Reset() {
	*x = ClassifyListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyListResp) ProtoMessage() {}

func (x *ClassifyListResp) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyListResp.ProtoReflect.Descriptor instead.
func (*ClassifyListResp) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{2}
}

func (x *ClassifyListResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ClassifyListResp) GetData() []*ClassifyListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClassifyRetrieveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassifyId int64 `protobuf:"varint,1,opt,name=classifyId,proto3" json:"classifyId,omitempty"`
}

func (x *ClassifyRetrieveReq) Reset() {
	*x = ClassifyRetrieveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyRetrieveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRetrieveReq) ProtoMessage() {}

func (x *ClassifyRetrieveReq) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRetrieveReq.ProtoReflect.Descriptor instead.
func (*ClassifyRetrieveReq) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{3}
}

func (x *ClassifyRetrieveReq) GetClassifyId() int64 {
	if x != nil {
		return x.ClassifyId
	}
	return 0
}

type ClassifyRetrieveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassifyId int64  `protobuf:"varint,1,opt,name=classifyId,proto3" json:"classifyId,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ClassifyRetrieveResp) Reset() {
	*x = ClassifyRetrieveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyRetrieveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRetrieveResp) ProtoMessage() {}

func (x *ClassifyRetrieveResp) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRetrieveResp.ProtoReflect.Descriptor instead.
func (*ClassifyRetrieveResp) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{4}
}

func (x *ClassifyRetrieveResp) GetClassifyId() int64 {
	if x != nil {
		return x.ClassifyId
	}
	return 0
}

func (x *ClassifyRetrieveResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ClassifyAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreateBy int64  `protobuf:"varint,2,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy int64  `protobuf:"varint,3,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
}

func (x *ClassifyAddReq) Reset() {
	*x = ClassifyAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyAddReq) ProtoMessage() {}

func (x *ClassifyAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyAddReq.ProtoReflect.Descriptor instead.
func (*ClassifyAddReq) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{5}
}

func (x *ClassifyAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassifyAddReq) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *ClassifyAddReq) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

type ClassifyAddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClassifyAddResp) Reset() {
	*x = ClassifyAddResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyAddResp) ProtoMessage() {}

func (x *ClassifyAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyAddResp.ProtoReflect.Descriptor instead.
func (*ClassifyAddResp) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{6}
}

type ClassifyUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassifyId int64  `protobuf:"varint,1,opt,name=classifyId,proto3" json:"classifyId,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UpdateBy   int64  `protobuf:"varint,3,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
}

func (x *ClassifyUpdateReq) Reset() {
	*x = ClassifyUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyUpdateReq) ProtoMessage() {}

func (x *ClassifyUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyUpdateReq.ProtoReflect.Descriptor instead.
func (*ClassifyUpdateReq) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{7}
}

func (x *ClassifyUpdateReq) GetClassifyId() int64 {
	if x != nil {
		return x.ClassifyId
	}
	return 0
}

func (x *ClassifyUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassifyUpdateReq) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

type ClassifyUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClassifyUpdateResp) Reset() {
	*x = ClassifyUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyUpdateResp) ProtoMessage() {}

func (x *ClassifyUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyUpdateResp.ProtoReflect.Descriptor instead.
func (*ClassifyUpdateResp) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{8}
}

type ClassifyDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassifyId int64 `protobuf:"varint,1,opt,name=classifyId,proto3" json:"classifyId,omitempty"`
}

func (x *ClassifyDeleteReq) Reset() {
	*x = ClassifyDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyDeleteReq) ProtoMessage() {}

func (x *ClassifyDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyDeleteReq.ProtoReflect.Descriptor instead.
func (*ClassifyDeleteReq) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{9}
}

func (x *ClassifyDeleteReq) GetClassifyId() int64 {
	if x != nil {
		return x.ClassifyId
	}
	return 0
}

type ClassifyDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClassifyDeleteResp) Reset() {
	*x = ClassifyDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyDeleteResp) ProtoMessage() {}

func (x *ClassifyDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyDeleteResp.ProtoReflect.Descriptor instead.
func (*ClassifyDeleteResp) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{10}
}

// template start
type TemplateListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *TemplateListReq) Reset() {
	*x = TemplateListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateListReq) ProtoMessage() {}

func (x *TemplateListReq) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateListReq.ProtoReflect.Descriptor instead.
func (*TemplateListReq) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{11}
}

func (x *TemplateListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TemplateListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type TemplateListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId    int64  `protobuf:"varint,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FormStructure string `protobuf:"bytes,3,opt,name=form_structure,json=formStructure,proto3" json:"form_structure,omitempty"`
	Remark        string `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateBy      int64  `protobuf:"varint,5,opt,name=createBy,proto3" json:"createBy,omitempty"`
	CreatedAt     string `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdateBy      int64  `protobuf:"varint,7,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	UpdatedAt     string `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *TemplateListData) Reset() {
	*x = TemplateListData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateListData) ProtoMessage() {}

func (x *TemplateListData) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateListData.ProtoReflect.Descriptor instead.
func (*TemplateListData) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{12}
}

func (x *TemplateListData) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *TemplateListData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateListData) GetFormStructure() string {
	if x != nil {
		return x.FormStructure
	}
	return ""
}

func (x *TemplateListData) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *TemplateListData) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *TemplateListData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TemplateListData) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *TemplateListData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TemplateListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64               `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Data  []*TemplateListData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *TemplateListResp) Reset() {
	*x = TemplateListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateListResp) ProtoMessage() {}

func (x *TemplateListResp) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateListResp.ProtoReflect.Descriptor instead.
func (*TemplateListResp) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{13}
}

func (x *TemplateListResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TemplateListResp) GetData() []*TemplateListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TemplateRetrieveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId int64 `protobuf:"varint,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
}

func (x *TemplateRetrieveReq) Reset() {
	*x = TemplateRetrieveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateRetrieveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateRetrieveReq) ProtoMessage() {}

func (x *TemplateRetrieveReq) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateRetrieveReq.ProtoReflect.Descriptor instead.
func (*TemplateRetrieveReq) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{14}
}

func (x *TemplateRetrieveReq) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

type TemplateRetrieveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId    int64  `protobuf:"varint,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FormStructure string `protobuf:"bytes,3,opt,name=form_structure,json=formStructure,proto3" json:"form_structure,omitempty"`
	Remark        string `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *TemplateRetrieveResp) Reset() {
	*x = TemplateRetrieveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateRetrieveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateRetrieveResp) ProtoMessage() {}

func (x *TemplateRetrieveResp) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateRetrieveResp.ProtoReflect.Descriptor instead.
func (*TemplateRetrieveResp) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{15}
}

func (x *TemplateRetrieveResp) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *TemplateRetrieveResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateRetrieveResp) GetFormStructure() string {
	if x != nil {
		return x.FormStructure
	}
	return ""
}

func (x *TemplateRetrieveResp) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type TemplateAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FormStructure string `protobuf:"bytes,2,opt,name=form_structure,json=formStructure,proto3" json:"form_structure,omitempty"`
	Remark        string `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateBy      int64  `protobuf:"varint,4,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      int64  `protobuf:"varint,5,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
}

func (x *TemplateAddReq) Reset() {
	*x = TemplateAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateAddReq) ProtoMessage() {}

func (x *TemplateAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateAddReq.ProtoReflect.Descriptor instead.
func (*TemplateAddReq) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{16}
}

func (x *TemplateAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateAddReq) GetFormStructure() string {
	if x != nil {
		return x.FormStructure
	}
	return ""
}

func (x *TemplateAddReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *TemplateAddReq) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *TemplateAddReq) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

type TemplateAddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TemplateAddResp) Reset() {
	*x = TemplateAddResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateAddResp) ProtoMessage() {}

func (x *TemplateAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateAddResp.ProtoReflect.Descriptor instead.
func (*TemplateAddResp) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{17}
}

type TemplateUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId    int64  `protobuf:"varint,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FormStructure string `protobuf:"bytes,3,opt,name=form_structure,json=formStructure,proto3" json:"form_structure,omitempty"`
	Remark        string `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	UpdateBy      int64  `protobuf:"varint,5,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
}

func (x *TemplateUpdateReq) Reset() {
	*x = TemplateUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateUpdateReq) ProtoMessage() {}

func (x *TemplateUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateUpdateReq.ProtoReflect.Descriptor instead.
func (*TemplateUpdateReq) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{18}
}

func (x *TemplateUpdateReq) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *TemplateUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateUpdateReq) GetFormStructure() string {
	if x != nil {
		return x.FormStructure
	}
	return ""
}

func (x *TemplateUpdateReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *TemplateUpdateReq) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

type TemplateUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TemplateUpdateResp) Reset() {
	*x = TemplateUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateUpdateResp) ProtoMessage() {}

func (x *TemplateUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateUpdateResp.ProtoReflect.Descriptor instead.
func (*TemplateUpdateResp) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{19}
}

type TemplateDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId int64 `protobuf:"varint,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
}

func (x *TemplateDeleteReq) Reset() {
	*x = TemplateDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateDeleteReq) ProtoMessage() {}

func (x *TemplateDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateDeleteReq.ProtoReflect.Descriptor instead.
func (*TemplateDeleteReq) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{20}
}

func (x *TemplateDeleteReq) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

type TemplateDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TemplateDeleteResp) Reset() {
	*x = TemplateDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wkf_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateDeleteResp) ProtoMessage() {}

func (x *TemplateDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_wkf_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateDeleteResp.ProtoReflect.Descriptor instead.
func (*TemplateDeleteResp) Descriptor() ([]byte, []int) {
	return file_wkf_proto_rawDescGZIP(), []int{21}
}

var File_wkf_proto protoreflect.FileDescriptor

var file_wkf_proto_rawDesc = []byte{
	0x0a, 0x09, 0x77, 0x6b, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x77, 0x6b, 0x66,
	0x22, 0x39, 0x0a, 0x0f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0xba, 0x01, 0x0a, 0x10,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x53, 0x0a, 0x10, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x35, 0x0a,
	0x13, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x66, 0x79, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x14, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x5c, 0x0a, 0x0e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x22, 0x11,
	0x0a, 0x0f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x63, 0x0a, 0x11, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x66, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x66, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x33, 0x0a, 0x11,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x49,
	0x64, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x39, 0x0a, 0x0f, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x22, 0xf9, 0x01, 0x0a, 0x10, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x66,
	0x6f, 0x72, 0x6d, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x53,
	0x0a, 0x10, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x35, 0x0a, 0x13, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x14, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x6f, 0x72, 0x6d, 0x5f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x9b, 0x01, 0x0a, 0x0e, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x42, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x42, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0xa2, 0x01, 0x0a, 0x11, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x6f, 0x72, 0x6d, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x22, 0x14, 0x0a, 0x12,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x33, 0x0a, 0x11, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x32, 0x91, 0x05,
	0x0a, 0x03, 0x57, 0x6b, 0x66, 0x12, 0x3b, 0x0a, 0x0c, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x77, 0x6b,
	0x66, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x47, 0x0a, 0x10, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x12, 0x18, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x69, 0x66, 0x79, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x19, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x0b, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x41, 0x64, 0x64, 0x12, 0x13, 0x2e, 0x77, 0x6b, 0x66,
	0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x14, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x17, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0e, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x77, 0x6b, 0x66,
	0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x17, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0c, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x77, 0x6b,
	0x66, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x15, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x47, 0x0a, 0x10, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x12, 0x18, 0x2e, 0x77,
	0x6b, 0x66, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x38, 0x0a, 0x0b, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64,
	0x12, 0x13, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0e, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e,
	0x77, 0x6b, 0x66, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41,
	0x0a, 0x0e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x16, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x77, 0x6b, 0x66, 0x2e, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x77, 0x6b, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_wkf_proto_rawDescOnce sync.Once
	file_wkf_proto_rawDescData = file_wkf_proto_rawDesc
)

func file_wkf_proto_rawDescGZIP() []byte {
	file_wkf_proto_rawDescOnce.Do(func() {
		file_wkf_proto_rawDescData = protoimpl.X.CompressGZIP(file_wkf_proto_rawDescData)
	})
	return file_wkf_proto_rawDescData
}

var file_wkf_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_wkf_proto_goTypes = []interface{}{
	(*ClassifyListReq)(nil),      // 0: wkf.ClassifyListReq
	(*ClassifyListData)(nil),     // 1: wkf.ClassifyListData
	(*ClassifyListResp)(nil),     // 2: wkf.ClassifyListResp
	(*ClassifyRetrieveReq)(nil),  // 3: wkf.ClassifyRetrieveReq
	(*ClassifyRetrieveResp)(nil), // 4: wkf.ClassifyRetrieveResp
	(*ClassifyAddReq)(nil),       // 5: wkf.ClassifyAddReq
	(*ClassifyAddResp)(nil),      // 6: wkf.ClassifyAddResp
	(*ClassifyUpdateReq)(nil),    // 7: wkf.ClassifyUpdateReq
	(*ClassifyUpdateResp)(nil),   // 8: wkf.ClassifyUpdateResp
	(*ClassifyDeleteReq)(nil),    // 9: wkf.ClassifyDeleteReq
	(*ClassifyDeleteResp)(nil),   // 10: wkf.ClassifyDeleteResp
	(*TemplateListReq)(nil),      // 11: wkf.TemplateListReq
	(*TemplateListData)(nil),     // 12: wkf.TemplateListData
	(*TemplateListResp)(nil),     // 13: wkf.TemplateListResp
	(*TemplateRetrieveReq)(nil),  // 14: wkf.TemplateRetrieveReq
	(*TemplateRetrieveResp)(nil), // 15: wkf.TemplateRetrieveResp
	(*TemplateAddReq)(nil),       // 16: wkf.TemplateAddReq
	(*TemplateAddResp)(nil),      // 17: wkf.TemplateAddResp
	(*TemplateUpdateReq)(nil),    // 18: wkf.TemplateUpdateReq
	(*TemplateUpdateResp)(nil),   // 19: wkf.TemplateUpdateResp
	(*TemplateDeleteReq)(nil),    // 20: wkf.TemplateDeleteReq
	(*TemplateDeleteResp)(nil),   // 21: wkf.TemplateDeleteResp
}
var file_wkf_proto_depIdxs = []int32{
	1,  // 0: wkf.ClassifyListResp.data:type_name -> wkf.ClassifyListData
	12, // 1: wkf.TemplateListResp.data:type_name -> wkf.TemplateListData
	0,  // 2: wkf.Wkf.ClassifyList:input_type -> wkf.ClassifyListReq
	3,  // 3: wkf.Wkf.ClassifyRetrieve:input_type -> wkf.ClassifyRetrieveReq
	5,  // 4: wkf.Wkf.ClassifyAdd:input_type -> wkf.ClassifyAddReq
	7,  // 5: wkf.Wkf.ClassifyUpdate:input_type -> wkf.ClassifyUpdateReq
	9,  // 6: wkf.Wkf.ClassifyDelete:input_type -> wkf.ClassifyDeleteReq
	11, // 7: wkf.Wkf.TemplateList:input_type -> wkf.TemplateListReq
	14, // 8: wkf.Wkf.TemplateRetrieve:input_type -> wkf.TemplateRetrieveReq
	16, // 9: wkf.Wkf.TemplateAdd:input_type -> wkf.TemplateAddReq
	18, // 10: wkf.Wkf.TemplateUpdate:input_type -> wkf.TemplateUpdateReq
	20, // 11: wkf.Wkf.TemplateDelete:input_type -> wkf.TemplateDeleteReq
	2,  // 12: wkf.Wkf.ClassifyList:output_type -> wkf.ClassifyListResp
	4,  // 13: wkf.Wkf.ClassifyRetrieve:output_type -> wkf.ClassifyRetrieveResp
	6,  // 14: wkf.Wkf.ClassifyAdd:output_type -> wkf.ClassifyAddResp
	8,  // 15: wkf.Wkf.ClassifyUpdate:output_type -> wkf.ClassifyUpdateResp
	10, // 16: wkf.Wkf.ClassifyDelete:output_type -> wkf.ClassifyDeleteResp
	13, // 17: wkf.Wkf.TemplateList:output_type -> wkf.TemplateListResp
	15, // 18: wkf.Wkf.TemplateRetrieve:output_type -> wkf.TemplateRetrieveResp
	17, // 19: wkf.Wkf.TemplateAdd:output_type -> wkf.TemplateAddResp
	19, // 20: wkf.Wkf.TemplateUpdate:output_type -> wkf.TemplateUpdateResp
	21, // 21: wkf.Wkf.TemplateDelete:output_type -> wkf.TemplateDeleteResp
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_wkf_proto_init() }
func file_wkf_proto_init() {
	if File_wkf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wkf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyListData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyRetrieveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyRetrieveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyAddResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateListData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateRetrieveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateRetrieveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateAddResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wkf_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wkf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wkf_proto_goTypes,
		DependencyIndexes: file_wkf_proto_depIdxs,
		MessageInfos:      file_wkf_proto_msgTypes,
	}.Build()
	File_wkf_proto = out.File
	file_wkf_proto_rawDesc = nil
	file_wkf_proto_goTypes = nil
	file_wkf_proto_depIdxs = nil
}
