// Code generated by goctl. DO NOT EDIT.
package types

type PageReq struct {
	PageIndex int64 `form:"pageIndex,default=1"`
	PageSize  int64 `form:"pageSize,default=20"`
}

type Pagination struct {
	PageIndex int64 `json:"pageIndex"`
	PageSize  int64 `json:"pageSize"`
	Count     int64 `json:"count"`
}

type ClassifyListReq struct {
	PageReq
}

type ClassifyListData struct {
	ClassifyId int64  `json:"classifyId"`
	Name       string `json:"name"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
	CreateBy   int64  `json:"createBy"`
	UpdateBy   int64  `json:"updateBy"`
}

type ClassifyListResp struct {
	List []ClassifyListData `json:"list"`
	Pagination
}

type ClassifyRetrieveReq struct {
	ClassifyId int64 `path:"classifyId"`
}

type ClassifyRetrieveResp struct {
	ClassifyId int64  `json:"classifyId"`
	Name       string `json:"name"`
}

type ClassifyAddReq struct {
	Name     string `json:"name"`
	CreateBy int64  `json:"createBy,optional"`
	UpdateBy int64  `json:"updateBy,optional"`
}

type ClassifyUpdateReq struct {
	ClassifyId int64  `json:"classifyId"`
	Name       string `json:"name"`
	UpdateBy   int64  `json:"updateBy,optional"`
}

type ClassifyDeleteReq struct {
	ClassifyId int64 `path:"classifyId"`
}

type TemplateListReq struct {
	PageReq
}

type TemplateListData struct {
	TemplateId    int64  `json:"templateId"`
	Name          string `json:"name"`
	FormStructure string `json:"form_structure"`
	Remark        string `json:"remark"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
	CreateBy      int64  `json:"createBy"`
	UpdateBy      int64  `json:"updateBy"`
}

type TemplateListResp struct {
	List []TemplateListData `json:"list"`
	Pagination
}

type TemplateRetrieveReq struct {
	TemplateId int64 `path:"templateId"`
}

type TemplateRetrieveResp struct {
	TemplateId    int64  `json:"templateId"`
	Name          string `json:"name"`
	FormStructure string `json:"form_structure"`
	Remark        string `json:"remark"`
}

type TemplateAddReq struct {
	Name          string `json:"name"`
	FormStructure string `json:"form_structure"`
	Remark        string `json:"remark"`
	CreateBy      int64  `json:"createBy,optional"`
	UpdateBy      int64  `json:"updateBy,optional"`
}

type TemplateUpdateReq struct {
	TemplateId    int64  `json:"templateId"`
	Name          string `json:"name"`
	FormStructure string `json:"form_structure"`
	Remark        string `json:"remark"`
	UpdateBy      int64  `json:"updateBy,optional"`
}

type TemplateDeleteReq struct {
	TemplateId int64 `path:"templateId"`
}
