// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	classify "github.com/yongxin/zen/service/workflow/api/internal/handler/classify"
	"github.com/yongxin/zen/service/workflow/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/classify",
				Handler: classify.ClassifyListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/classify/:classifyId",
				Handler: classify.ClassifyRetrieveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/classify",
				Handler: classify.ClassifyAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/classify/:classifyId",
				Handler: classify.ClassifyUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/classify/:classifyId",
				Handler: classify.ClassifyDeleteHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/workflow"),
	)
}
