// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	wkfClassifyFieldNames          = builder.RawFieldNames(&WkfClassify{})
	wkfClassifyRows                = strings.Join(wkfClassifyFieldNames, ",")
	wkfClassifyRowsExpectAutoSet   = strings.Join(stringx.Remove(wkfClassifyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	wkfClassifyRowsWithPlaceHolder = strings.Join(stringx.Remove(wkfClassifyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheWkfClassifyIdPrefix = "cache:wkfClassify:id:"
)

type (
	wkfClassifyModel interface {
		Insert(ctx context.Context, data *WkfClassify) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WkfClassify, error)
		Update(ctx context.Context, data *WkfClassify) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWkfClassifyModel struct {
		sqlc.CachedConn
		table string
	}

	WkfClassify struct {
		Id       int64     `db:"id"`        // 编码
		Name     string    `db:"name"`      // 名称
		CreateBy int64     `db:"create_by"` // 创建者
		UpdateBy int64     `db:"update_by"` // 更新者
		CreateAt time.Time `db:"create_at"` // 创建时间
		UpdateAt time.Time `db:"update_at"` // 更新时间
	}
)

func newWkfClassifyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWkfClassifyModel {
	return &defaultWkfClassifyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`wkf_classify`",
	}
}

func (m *defaultWkfClassifyModel) withSession(session sqlx.Session) *defaultWkfClassifyModel {
	return &defaultWkfClassifyModel{
		CachedConn: m.CachedConn.WithSession(session),
		table:      "`wkf_classify`",
	}
}

func (m *defaultWkfClassifyModel) Delete(ctx context.Context, id int64) error {
	wkfClassifyIdKey := fmt.Sprintf("%s%v", cacheWkfClassifyIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, wkfClassifyIdKey)
	return err
}

func (m *defaultWkfClassifyModel) FindOne(ctx context.Context, id int64) (*WkfClassify, error) {
	wkfClassifyIdKey := fmt.Sprintf("%s%v", cacheWkfClassifyIdPrefix, id)
	var resp WkfClassify
	err := m.QueryRowCtx(ctx, &resp, wkfClassifyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wkfClassifyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWkfClassifyModel) Insert(ctx context.Context, data *WkfClassify) (sql.Result, error) {
	wkfClassifyIdKey := fmt.Sprintf("%s%v", cacheWkfClassifyIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, wkfClassifyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.CreateBy, data.UpdateBy)
	}, wkfClassifyIdKey)
	return ret, err
}

func (m *defaultWkfClassifyModel) Update(ctx context.Context, data *WkfClassify) error {
	wkfClassifyIdKey := fmt.Sprintf("%s%v", cacheWkfClassifyIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, wkfClassifyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.CreateBy, data.UpdateBy, data.Id)
	}, wkfClassifyIdKey)
	return err
}

func (m *defaultWkfClassifyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheWkfClassifyIdPrefix, primary)
}

func (m *defaultWkfClassifyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wkfClassifyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWkfClassifyModel) tableName() string {
	return m.table
}
