// Code generated by goctl. DO NOT EDIT.
// Source: wkf.proto

package server

import (
	"context"

	"github.com/yongxin/zen/service/workflow/rpc/internal/logic"
	"github.com/yongxin/zen/service/workflow/rpc/internal/svc"
	"github.com/yongxin/zen/service/workflow/rpc/wkf"
)

type WkfServer struct {
	svcCtx *svc.ServiceContext
	wkf.UnimplementedWkfServer
}

func NewWkfServer(svcCtx *svc.ServiceContext) *WkfServer {
	return &WkfServer{
		svcCtx: svcCtx,
	}
}

func (s *WkfServer) ClassifyList(ctx context.Context, in *wkf.ClassifyListReq) (*wkf.ClassifyListResp, error) {
	l := logic.NewClassifyListLogic(ctx, s.svcCtx)
	return l.ClassifyList(in)
}

func (s *WkfServer) ClassifyRetrieve(ctx context.Context, in *wkf.ClassifyRetrieveReq) (*wkf.ClassifyRetrieveResp, error) {
	l := logic.NewClassifyRetrieveLogic(ctx, s.svcCtx)
	return l.ClassifyRetrieve(in)
}

func (s *WkfServer) ClassifyAdd(ctx context.Context, in *wkf.ClassifyAddReq) (*wkf.ClassifyAddResp, error) {
	l := logic.NewClassifyAddLogic(ctx, s.svcCtx)
	return l.ClassifyAdd(in)
}

func (s *WkfServer) ClassifyUpdate(ctx context.Context, in *wkf.ClassifyUpdateReq) (*wkf.ClassifyUpdateResp, error) {
	l := logic.NewClassifyUpdateLogic(ctx, s.svcCtx)
	return l.ClassifyUpdate(in)
}

func (s *WkfServer) ClassifyDelete(ctx context.Context, in *wkf.ClassifyDeleteReq) (*wkf.ClassifyDeleteResp, error) {
	l := logic.NewClassifyDeleteLogic(ctx, s.svcCtx)
	return l.ClassifyDelete(in)
}

func (s *WkfServer) TemplateList(ctx context.Context, in *wkf.TemplateListReq) (*wkf.TemplateListResp, error) {
	l := logic.NewTemplateListLogic(ctx, s.svcCtx)
	return l.TemplateList(in)
}

func (s *WkfServer) TemplateRetrieve(ctx context.Context, in *wkf.TemplateRetrieveReq) (*wkf.TemplateRetrieveResp, error) {
	l := logic.NewTemplateRetrieveLogic(ctx, s.svcCtx)
	return l.TemplateRetrieve(in)
}

func (s *WkfServer) TemplateAdd(ctx context.Context, in *wkf.TemplateAddReq) (*wkf.TemplateAddResp, error) {
	l := logic.NewTemplateAddLogic(ctx, s.svcCtx)
	return l.TemplateAdd(in)
}

func (s *WkfServer) TemplateUpdate(ctx context.Context, in *wkf.TemplateUpdateReq) (*wkf.TemplateUpdateResp, error) {
	l := logic.NewTemplateUpdateLogic(ctx, s.svcCtx)
	return l.TemplateUpdate(in)
}

func (s *WkfServer) TemplateDelete(ctx context.Context, in *wkf.TemplateDeleteReq) (*wkf.TemplateDeleteResp, error) {
	l := logic.NewTemplateDeleteLogic(ctx, s.svcCtx)
	return l.TemplateDelete(in)
}
