// Code generated by goctl. DO NOT EDIT.
// Source: wkf.proto

package server

import (
	"context"

	"github.com/yongxin/zen/service/workflow/rpc/internal/logic"
	"github.com/yongxin/zen/service/workflow/rpc/internal/svc"
	"github.com/yongxin/zen/service/workflow/rpc/wkf"
)

type WkfServer struct {
	svcCtx *svc.ServiceContext
	wkf.UnimplementedWkfServer
}

func NewWkfServer(svcCtx *svc.ServiceContext) *WkfServer {
	return &WkfServer{
		svcCtx: svcCtx,
	}
}

func (s *WkfServer) ClassifyList(ctx context.Context, in *wkf.ClassifyListReq) (*wkf.ClassifyListResp, error) {
	l := logic.NewClassifyListLogic(ctx, s.svcCtx)
	return l.ClassifyList(in)
}

func (s *WkfServer) ClassifyRetrieve(ctx context.Context, in *wkf.ClassifyRetrieveReq) (*wkf.ClassifyRetrieveResp, error) {
	l := logic.NewClassifyRetrieveLogic(ctx, s.svcCtx)
	return l.ClassifyRetrieve(in)
}

func (s *WkfServer) ClassifyAdd(ctx context.Context, in *wkf.ClassifyAddReq) (*wkf.ClassifyAddResp, error) {
	l := logic.NewClassifyAddLogic(ctx, s.svcCtx)
	return l.ClassifyAdd(in)
}

func (s *WkfServer) ClassifyUpdate(ctx context.Context, in *wkf.ClassifyUpdateReq) (*wkf.ClassifyUpdateResp, error) {
	l := logic.NewClassifyUpdateLogic(ctx, s.svcCtx)
	return l.ClassifyUpdate(in)
}

func (s *WkfServer) ClassifyDelete(ctx context.Context, in *wkf.ClassifyDeleteReq) (*wkf.ClassifyDeleteResp, error) {
	l := logic.NewClassifyDeleteLogic(ctx, s.svcCtx)
	return l.ClassifyDelete(in)
}

func (s *WkfServer) TemplateList(ctx context.Context, in *wkf.TemplateListReq) (*wkf.TemplateListResp, error) {
	l := logic.NewTemplateListLogic(ctx, s.svcCtx)
	return l.TemplateList(in)
}

func (s *WkfServer) TemplateRetrieve(ctx context.Context, in *wkf.TemplateRetrieveReq) (*wkf.TemplateRetrieveResp, error) {
	l := logic.NewTemplateRetrieveLogic(ctx, s.svcCtx)
	return l.TemplateRetrieve(in)
}

func (s *WkfServer) TemplateAdd(ctx context.Context, in *wkf.TemplateAddReq) (*wkf.TemplateAddResp, error) {
	l := logic.NewTemplateAddLogic(ctx, s.svcCtx)
	return l.TemplateAdd(in)
}

func (s *WkfServer) TemplateUpdate(ctx context.Context, in *wkf.TemplateUpdateReq) (*wkf.TemplateUpdateResp, error) {
	l := logic.NewTemplateUpdateLogic(ctx, s.svcCtx)
	return l.TemplateUpdate(in)
}

func (s *WkfServer) TemplateDelete(ctx context.Context, in *wkf.TemplateDeleteReq) (*wkf.TemplateDeleteResp, error) {
	l := logic.NewTemplateDeleteLogic(ctx, s.svcCtx)
	return l.TemplateDelete(in)
}

func (s *WkfServer) TaskList(ctx context.Context, in *wkf.TaskListReq) (*wkf.TaskListResp, error) {
	l := logic.NewTaskListLogic(ctx, s.svcCtx)
	return l.TaskList(in)
}

func (s *WkfServer) TaskRetrieve(ctx context.Context, in *wkf.TaskRetrieveReq) (*wkf.TaskRetrieveResp, error) {
	l := logic.NewTaskRetrieveLogic(ctx, s.svcCtx)
	return l.TaskRetrieve(in)
}

func (s *WkfServer) TaskAdd(ctx context.Context, in *wkf.TaskAddReq) (*wkf.TaskAddResp, error) {
	l := logic.NewTaskAddLogic(ctx, s.svcCtx)
	return l.TaskAdd(in)
}

func (s *WkfServer) TaskUpdate(ctx context.Context, in *wkf.TaskUpdateReq) (*wkf.TaskUpdateResp, error) {
	l := logic.NewTaskUpdateLogic(ctx, s.svcCtx)
	return l.TaskUpdate(in)
}

func (s *WkfServer) TaskDelete(ctx context.Context, in *wkf.TaskDeleteReq) (*wkf.TaskDeleteResp, error) {
	l := logic.NewTaskDeleteLogic(ctx, s.svcCtx)
	return l.TaskDelete(in)
}

func (s *WkfServer) ProcessList(ctx context.Context, in *wkf.ProcessListReq) (*wkf.ProcessListResp, error) {
	l := logic.NewProcessListLogic(ctx, s.svcCtx)
	return l.ProcessList(in)
}

func (s *WkfServer) ProcessRetrieve(ctx context.Context, in *wkf.ProcessRetrieveReq) (*wkf.ProcessRetrieveResp, error) {
	l := logic.NewProcessRetrieveLogic(ctx, s.svcCtx)
	return l.ProcessRetrieve(in)
}

func (s *WkfServer) ProcessAdd(ctx context.Context, in *wkf.ProcessAddReq) (*wkf.ProcessAddResp, error) {
	l := logic.NewProcessAddLogic(ctx, s.svcCtx)
	return l.ProcessAdd(in)
}

func (s *WkfServer) ProcessUpdate(ctx context.Context, in *wkf.ProcessUpdateReq) (*wkf.ProcessUpdateResp, error) {
	l := logic.NewProcessUpdateLogic(ctx, s.svcCtx)
	return l.ProcessUpdate(in)
}

func (s *WkfServer) ProcessDelete(ctx context.Context, in *wkf.ProcessDeleteReq) (*wkf.ProcessDeleteResp, error) {
	l := logic.NewProcessDeleteLogic(ctx, s.svcCtx)
	return l.ProcessDelete(in)
}

func (s *WkfServer) ProcessClassify(ctx context.Context, in *wkf.ProcessClassifyReq) (*wkf.ProcessClassifyResp, error) {
	l := logic.NewProcessClassifyLogic(ctx, s.svcCtx)
	return l.ProcessClassify(in)
}

func (s *WkfServer) TicketProcess(ctx context.Context, in *wkf.TicketProcessReq) (*wkf.TicketProcessResp, error) {
	l := logic.NewTicketProcessLogic(ctx, s.svcCtx)
	return l.TicketProcess(in)
}

func (s *WkfServer) TicketList(ctx context.Context, in *wkf.TicketListReq) (*wkf.TicketListResp, error) {
	l := logic.NewTicketListLogic(ctx, s.svcCtx)
	return l.TicketList(in)
}

func (s *WkfServer) TicketAdd(ctx context.Context, in *wkf.TicketAddReq) (*wkf.TicketAddResp, error) {
	l := logic.NewTicketAddLogic(ctx, s.svcCtx)
	return l.TicketAdd(in)
}

func (s *WkfServer) TicketHandle(ctx context.Context, in *wkf.TicketHandleReq) (*wkf.TicketHandleResp, error) {
	l := logic.NewTicketHandleLogic(ctx, s.svcCtx)
	return l.TicketHandle(in)
}
